name: gooseberrymoon
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4596762568689883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c4c5c7'
    - '#8c8d92'
    - '#3a455b'
    - '#666e7f'
  brandStrength: 0.9367370319087058
  lightness: 0.75
  saturation: 0.5087844259105623
  rhythmicContrast: 0.2523639784194529
purpose: []
