name: gooseberrymoon
favicon: null
layout_spectrum: 0.24799504363909364
typography_spectrum: 0.4596762568689883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9367370319087058
  lightness: 0.22054762276820838
  saturation: 0.5087844259105623
  rhythmicContrast: 0.2523639784194529
purpose: []
